# Generated by Django 5.0.4 on 2024-05-03 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alergia_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alergias',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='aluno_udc',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='contato',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='contato_emergencia',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='escolaridade',
            field=models.CharField(choices=[('fundamental', 'Fundamental'), ('medio', 'Médio'), ('superior', 'Superior'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='filho',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 18, 48, 0, 585167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='profissao',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='qtd_filhos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='raca',
            field=models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='rede_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3),
        ),
    ]
